# Generated by Django 5.2.1 on 2025-07-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctor_horarios_atencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Consulta General, Radiografía de Tórax, Análisis de Sangre', max_length=100, unique=True, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, help_text='Detalle del servicio ofrecido.', null=True, verbose_name='Descripción del Servicio')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Costo del servicio.', max_digits=10, verbose_name='Precio')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el servicio está disponible.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
