# Generated by Django 5.2.2 on 2025-07-03 21:08

from django.db import migrations


def create_initial_services(apps, schema_editor):
    Servicio = apps.get_model('core', 'Servicio')
    db_alias = schema_editor.connection.alias

    initial_services = [
        {"nombre": "Consulta General", "descripcion": "Consulta médica de rutina o seguimiento.", "precio": 30.00},
        {"nombre": "Radiografía de Tórax", "descripcion": "Estudio de imagen para evaluar pulmones y corazón.", "precio": 50.00},
        {"nombre": "Análisis de Sangre Completo", "descripcion": "Hemograma completo, química sanguínea, perfil lipídico.", "precio": 45.00},
        {"nombre": "Análisis de Orina", "descripcion": "Examen general de orina para detectar infecciones o problemas renales.", "precio": 20.00},
        {"nombre": "Sutura de Herida Menor", "descripcion": "Cierre de heridas pequeñas con suturas.", "precio": 60.00},
        {"nombre": "Curación de Herida", "descripcion": "Limpieza y vendaje de heridas.", "precio": 25.00},
        {"nombre": "Inyección Intramuscular", "descripcion": "Administración de medicamentos vía intramuscular.", "precio": 15.00},
        {"nombre": "Control de Presión Arterial", "descripcion": "Medición y registro de la presión arterial.", "precio": 10.00},
        {"nombre": "Retiro de Puntos", "descripcion": "Remoción de suturas post-quirúrgicas.", "precio": 35.00},
        {"nombre": "Fisioterapia (Sesión)", "descripcion": "Sesión individual de terapia física.", "precio": 40.00},
    ]

    for service_data in initial_services:
        Servicio.objects.using(db_alias).get_or_create(
            nombre=service_data["nombre"],
            defaults={
                "descripcion": service_data["descripcion"],
                "precio": service_data["precio"],
                "activo": True
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicio'),
    ]

    operations = [
        migrations.RunPython(create_initial_services),
    ]
