# Generated by Django 5.2.1 on 2025-07-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicio'),
        ('doctor', '0005_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleServicioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de veces que se realizó el servicio.', verbose_name='Cantidad')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el servicio realizado.', null=True, verbose_name='Observaciones')),
                ('atencion', models.ForeignKey(help_text='Atención médica asociada a este servicio adicional.', on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='doctor.atencion', verbose_name='Atención Médica')),
                ('servicio', models.ForeignKey(help_text='Servicio adicional realizado durante la atención.', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_atencion', to='core.servicio', verbose_name='Servicio Adicional')),
            ],
            options={
                'verbose_name': 'Detalle de Servicio de Atención',
                'verbose_name_plural': 'Detalles de Servicios de Atención',
                'ordering': ['atencion', 'servicio'],
                'unique_together': {('atencion', 'servicio')},
            },
        ),
    ]
