# Generated by Django 5.2.1 on 2025-07-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_detalleservicioatencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='json_respuesta_paypal',
            field=models.JSONField(blank=True, null=True, verbose_name='Respuesta PayPal (JSON)'),
        ),
        migrations.AddField(
            model_name='pago',
            name='paypal_capture_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PayPal Capture ID'),
        ),
        migrations.AddField(
            model_name='pago',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PayPal Order ID'),
        ),
    ]
